id: AEDEEE6D0
title: Descent of Blessings of the Eight Vidyādharas
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:38:56.134182
  last_modified_at: 2022-03-01 03:38:56.134186
