id: AEDEEE6D0
title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme VidyÄdharas
  of India'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:38:56.131932
  last_modified_at: 2022-03-01 03:38:56.131940
